
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Usuario
 */
public class futbol extends javax.swing.JFrame {

    /**
     * Creates new form futbol
     */
    public futbol() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("REGISTRAR EQUIPO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("EDITAR EQUIPO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 131, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("ELIIMINAR EQUIPO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("LISTAR EQUIPO");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 131, -1));

        jLabel3.setBackground(new java.awt.Color(153, 255, 204));
        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("CAMPEONATO FUTSAL UFC");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 180, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\OneDrive\\Documentos\\NetBeansProjects\\Futbol_p\\src\\main\\java\\img\\chicas_aguila.jpg")); // NOI18N
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 689, 585));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //código para el botón de registrar o guardar equipo
                    JFrame nuevaVentana = new JFrame();
                    nuevaVentana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    nuevaVentana.setSize(350, 220);
                    nuevaVentana.setLocationRelativeTo(null);
                    nuevaVentana.setTitle("Agregar Equipo");
                    nuevaVentana.setVisible(true);
                    nuevaVentana.setResizable(false);
                    nuevaVentana.setLayout(null);
                    
                    JLabel labelID = new JLabel("ID:");
                    labelID.setBounds(30, 20, 100, 30);

                    JTextField textFieldID = new JTextField();
                    textFieldID.setBounds(170, 20, 150, 30);

                    JLabel labelNombreEquipo = new JLabel("Nombre Equipo:");
                    labelNombreEquipo.setBounds(30, 60, 100, 30);

                    JTextField textFieldNombreEquipo = new JTextField();
                    textFieldNombreEquipo.setBounds(170, 60, 150, 30);

                    JLabel labelNombreEntrenador = new JLabel("Nombre Entrenador:");
                    labelNombreEntrenador.setBounds(30, 100, 120, 30);
                    
                    JTextField textFieldNombreEntrenador = new JTextField();
                    textFieldNombreEntrenador.setBounds(170, 100, 150, 30);

                    JButton botonGuardar = new JButton("Guardar");
                    botonGuardar.setBounds(120, 140, 100, 30);
                    
                    botonGuardar.addActionListener(new ActionListener() {
                        public void actionPerformed(ActionEvent e) {
                            String id = textFieldID.getText();
                            String nombreEquipo = textFieldNombreEquipo.getText();
                            String nombreEntrenador = textFieldNombreEntrenador.getText();
                            
                                if (existeID(id)) {
                                    JOptionPane.showMessageDialog(null, "El ID ya esta en uso. Inténtalo con otro.");
                                return;
                                } else {
                                    try {

                                        BufferedWriter writer = new BufferedWriter(new FileWriter("datos.txt", true));
                                        writer.write(id + "," + nombreEquipo + "," + nombreEntrenador);
                                        writer.newLine();
                                        writer.close();
                                        JOptionPane.showMessageDialog(nuevaVentana, "Datos guardados correctamente.");
                                    } catch (IOException ex) {
                                        JOptionPane.showMessageDialog(nuevaVentana, "Error al guardar los datos.", "Error", JOptionPane.ERROR_MESSAGE);
                                        ex.printStackTrace();
                                    }
                                }
                            nuevaVentana.dispose();
                        }

                    private boolean existeID(String id) {
                        try {
                            BufferedReader reader = new BufferedReader(new FileReader("datos.txt"));
                            String line;
                            while ((line = reader.readLine()) != null) {
                                String[] datos = line.split(",");
                                if (datos.length >= 1 && datos[0].equals(id)) {
                                    reader.close();
                                    return true;
                                }
                            }
                            reader.close();
                        } catch (IOException e) {
                            e.printStackTrace();
                        }
                        return false; 
                    }

                    });     
                    nuevaVentana.add(labelID);
                    nuevaVentana.add(textFieldID);
                    nuevaVentana.add(labelNombreEquipo);
                    nuevaVentana.add(textFieldNombreEquipo);
                    nuevaVentana.add(labelNombreEntrenador);
                    nuevaVentana.add(textFieldNombreEntrenador);
                    nuevaVentana.add(botonGuardar);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //código para el botón de editar equipo
                    JFrame nuevaVentana = new JFrame();
                    nuevaVentana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    nuevaVentana.setSize(320, 230);
                    nuevaVentana.setLocationRelativeTo(null);
                    nuevaVentana.setTitle("Editar Equipo");
                    nuevaVentana.setVisible(true);
                    nuevaVentana.setResizable(false);
                    nuevaVentana.setLayout(null); 
                    
                    JLabel labelID = new JLabel("ID:");
                    labelID.setBounds(20, 20, 100, 30);
                    
                    JTextField textFieldID = new JTextField();
                    textFieldID.setBounds(120, 20, 150, 30);
                    
                    JLabel labelNombreEquipo = new JLabel("Nombre Equipo:");
                    labelNombreEquipo.setBounds(20, 60, 100, 30);
                    
                    JTextField textFieldNombreEquipo = new JTextField();
                    textFieldNombreEquipo.setBounds(120, 60, 150, 30);
                    
                    JLabel labelNombreEntrenador = new JLabel("Nombre Entrenador:");
                    labelNombreEntrenador.setBounds(20, 100, 100, 30);
                    
                    JTextField textFieldNombreEntrenador = new JTextField();
                    textFieldNombreEntrenador.setBounds(120, 100, 150, 30);
                    
                    JButton botonEditar = new JButton("Editar");
                    botonEditar.setBounds(120, 140, 100, 30);
                                        
                    botonEditar.addActionListener(new ActionListener() {
                        public void actionPerformed(ActionEvent e) {
                            String id = textFieldID.getText();
                            String nombreEquipo = textFieldNombreEquipo.getText();
                            String nombreEntrenador = textFieldNombreEntrenador.getText();
                            
                            try {
                                File inputFile = new File("datos.txt");
                                File tempFile = new File("temp.txt");
                                
                                BufferedReader reader = new BufferedReader(new FileReader(inputFile));
                                BufferedWriter writer = new BufferedWriter(new FileWriter(tempFile));
                                
                                String line;
                                boolean encontrado = false;
                                
                                while ((line = reader.readLine()) != null) {
                                    String[] datos = line.split(",");
                                    if (datos.length >= 3 && datos[0].equals(id)) {
                                        datos[1] = nombreEquipo;
                                        datos[2] = nombreEntrenador;
                                        line = String.join(",", datos);
                                        encontrado = true;
                                    }
                                    writer.write(line + System.lineSeparator());
                                }
                                
                                reader.close();
                                writer.close();
                                
                                if (encontrado) {
                                    inputFile.delete();
                                    tempFile.renameTo(inputFile);
                                    JOptionPane.showMessageDialog(nuevaVentana, "Equipo editado correctamente.");
                                } else {
                                    JOptionPane.showMessageDialog(nuevaVentana, "No se encontró un equipo con el ID proporcionado.");
                                }
                            } catch (IOException ex) {
                                JOptionPane.showMessageDialog(nuevaVentana, "Error al editar el equipo.");
                                ex.printStackTrace();
                            }

                            nuevaVentana.dispose();
                        }
                    });    
                    nuevaVentana.add(labelID);
                    nuevaVentana.add(textFieldID);
                    nuevaVentana.add(labelNombreEquipo);
                    nuevaVentana.add(textFieldNombreEquipo);
                    nuevaVentana.add(labelNombreEntrenador);
                    nuevaVentana.add(textFieldNombreEntrenador);
                    nuevaVentana.add(botonEditar);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //código para eliminar directamente un equipo

                    JFrame nuevaVentana = new JFrame();
                    nuevaVentana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    nuevaVentana.setSize(300, 150);
                    nuevaVentana.setLocationRelativeTo(null);
                    nuevaVentana.setTitle("Eliminar Equipo");
                    nuevaVentana.setVisible(true);
                    nuevaVentana.setResizable(false);
                    nuevaVentana.setLayout(null); 
                    
                    JLabel labelID = new JLabel("ID:");
                    labelID.setBounds(20, 20, 100, 30);
                    
                    JTextField textFieldID = new JTextField();
                    textFieldID.setBounds(120, 20, 150, 30);
                    
                    JButton botonEliminar = new JButton("Eliminar");
                    botonEliminar.setBounds(120, 60, 100, 30);
                    
                    botonEliminar.addActionListener(new ActionListener() {
                        public void actionPerformed(ActionEvent e) {
                            String id = textFieldID.getText();
                            
                            try {
                                File inputFile = new File("datos.txt");
                                File tempFile = new File("temp.txt");
                                
                                BufferedReader reader = new BufferedReader(new FileReader(inputFile));
                                BufferedWriter writer = new BufferedWriter(new FileWriter(tempFile));
                                
                                String line;
                                boolean encontrado = false;
                                
                                while ((line = reader.readLine()) != null) {
                                    String[] datos = line.split(",");
                                    if (datos.length >= 1 && datos[0].equals(id)) {
                                        encontrado = true;
                                        continue;
                                    }
                                    writer.write(line + System.lineSeparator());
                                }
                                
                                reader.close();
                                writer.close();
                                
                                if (encontrado) {
                                    inputFile.delete();
                                    tempFile.renameTo(inputFile);
                                    JOptionPane.showMessageDialog(nuevaVentana, "Equipo eliminado correctamente.");
                                } else {
                                    JOptionPane.showMessageDialog(nuevaVentana, "No se encontró un equipo con el ID proporcionado.", "Error", JOptionPane.ERROR_MESSAGE);
                                }
                            } catch (IOException ex) {
                                JOptionPane.showMessageDialog(nuevaVentana, "Error al eliminar el equipo.", "Error", JOptionPane.ERROR_MESSAGE);
                                ex.printStackTrace();
                            }

                            nuevaVentana.dispose();
                        }
                    });    
                    nuevaVentana.add(labelID);
                    nuevaVentana.add(textFieldID);
                    nuevaVentana.add(botonEliminar);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //código para listar todos los equipos

                    JFrame nuevaVentana = new JFrame();
                    nuevaVentana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    nuevaVentana.setSize(600, 400);
                    nuevaVentana.setLocationRelativeTo(null);
                    nuevaVentana.setTitle("Lista de Equipos");
                    nuevaVentana.setVisible(true);
                    nuevaVentana.setResizable(false);
                    nuevaVentana.setLayout(null); 
                    
                    DefaultTableModel tableModel = new DefaultTableModel();
                    tableModel.addColumn("ID");
                    tableModel.addColumn("Nombre Equipo");
                    tableModel.addColumn("Nombre Entrenador");

                    try (BufferedReader reader = new BufferedReader(new FileReader("datos.txt"))) {
                        String line;
                        while ((line = reader.readLine()) != null) {
                            String[] datos = line.split(",");
                            if (datos.length >= 3) {
                                tableModel.addRow(datos);
                            }
                        }
                    } catch (IOException e) {
                        e.printStackTrace();
                    }

                    JTable table = new JTable(tableModel);
                    

                        JScrollPane scrollPane = new JScrollPane(table);
                        scrollPane.setBounds(20, 20, 560, 320);

                        nuevaVentana.add(scrollPane);

                        nuevaVentana.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(futbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(futbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(futbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(futbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new futbol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
